### ISSUE TITLE
Design a baseboard for RPi CM4

### ISSUE THREAD

**Issue by tgorochowik** [antmicro-labs/open-source-video-previewer#1]
Design a baseboard for RPi CM4. Use Kicad: https://kicad.org/

The purpose of this task is to design a baseboard for the RPi CM4 (https://botland.com.pl/pl/raspberry-pi-cm/18179-raspberry-pi-cm4-compute-module-4-1gb-ram-8gb-emmc.html).

Base the design on the Jetson Nano baseboard released by Antmicro: https://github.com/antmicro/jetson-nano-baseboard
Note that this baseboard was designed in Altium Designer, therefore it cannot simply be modified. Feel free to base your design on it, but use Kicad instead.

Subtasks to do first:
* #4
* #3
* #2

After that initial work, start designing the board for the RPi CM4 module.

Keep the same form factor as the Jetson baseboard if possible.

Do not hesitate to ask questions and discuss the design here.

**Comment by pgielda** [comment]
Meanwhile we've open sourced another board that is a baseboard for RPi CM4:
https://github.com/antmicro/scalenode
Its worth checking out.

Its purpose is to be a PoE-powered 1U server compute node... But still exposes some of the features of CM4 like PCIe, sdcard, ethernet as well as HDMI and USB (on custom connectors) so it might also be used as a base/inspiration.

Its brand new so was not yet assembled and tested.
