### ISSUE TITLE
PCI-E

### ISSUE THREAD

**Issue by Magdalena22** [antmicro-labs/open-source-video-previewer#10]
Should we include pci-e connector or not?

**Comment by pgielda** [comment]
I would recommend keeping it. One of the things that Compute Module has that the original RPi does not is 1-lane PCIe.

**Comment by pkatarzynski** [comment]
If we are aiming at a baseboard similar to our Jetson Nano Baseboard It would be beneficial to expose that PCIe on M.2 or mPCIe card slot
