### ISSUE TITLE
Review the connectors on the Jetson Nano baseboard

### ISSUE THREAD

**Issue by tgorochowik** [antmicro-labs/open-source-video-previewer#2]
Verify that the external connectors used on the baseboard for Jetson Nano (https://github.com/antmicro/jetson-nano-baseboard) can be used with RPi CM4, if some of them make no sense (e.g. RPi does not have any peripherals that can utilize them), look for peripherals that RPi does offer and suggest other connectors.

**Comment by kgugala** [comment]
@antmicro-labs/lut-industrial-project any progress on this one?

**Comment by pkatarzynski** [comment]
Could you start from making a block diagram for the board that will describe the IOs? This block diagram can be embedded in KiCad's schematic or placed in the README.

If we take the Jetson Nano Baseboard as reference you can implement the following interfaes with RPi CM

Gigabit Ethernet 
CSI (number of available lanes and lane mapping needs to be verified) 
HDMI
PCIe (expoed as M.2 slot for instance)

Additionally it is possible to ad an SD card (it appeared in older revisions of the JNB but I has been dropped in the recent one)

I would drop a Displayport
