### ISSUE TITLE
Find/design schematics and part models for RPi CM4 module

### ISSUE THREAD

**Issue by tgorochowik** [antmicro-labs/open-source-video-previewer#3]
The purpose of this task is to find or design appropriate kicad library with the modules connectors that CM4 is equipped with.

Please note that we are likely to want to generate 3d previews for this board in the future, so the 3d models would be a nice addition too (either for the connectors alone or the CM4 module as a whole).

**Comment by kgugala** [comment]
@antmicro-labs/lut-industrial-project any progres on this one?

**Comment by pkatarzynski** [comment]
Well in the meantime we have prepared a scalenode based on CM4 - our OSHW projects have complete sets of libraries with 3D models (https://github.com/antmicro/scalenode/tree/master/lib). In 2-3 days we will know if the connectors and pinouts are OK as we are verifying the scalenode prototypes right now.

Also, please take a look at snapEDA (https://www.snapeda.com/)

We also use a lot of Wurth Elektronik components. Wurth has its own catalogue with symbols and 3D models (https://www.we-online.de/katalog/en)
