### ISSUE TITLE
Add initial README file

### ISSUE THREAD

**Issue by tgorochowik** [antmicro-labs/open-source-video-previewer#4]
Describe the goal of the project.

The README will need to be kept up to date as the project progresses.

**Comment by pgielda** [comment]
I would also strongly recommend adding a LICENSE file from the very beginning. Please use Apache 2.0. (this file https://github.com/antmicro/scalenode/blob/master/LICENSE)

**Comment by pkatarzynski** [comment]
Please add a block diagram for the board to README to indicate what interfaces are you going to implement
