### ISSUE TITLE
Board size

### ISSUE THREAD

**Issue by Magdalena22** [antmicro-labs/open-source-video-previewer#6]
Could it be the same as board with jetson nano (if technically possible to fit all elements)? Are there any size restrictions/recommendations?

**Comment by pkatarzynski** [comment]
I think it would be good to keep the 100x55mm outline to make the RPi baseboard similar to the [Jeston Nano Baseboard](https://github.com/antmicro/jetson-nano-baseboard) or [Google Coral Baseboard](https://github.com/antmicro/google-coral-baseboard)
