### ISSUE TITLE
Components source

### ISSUE THREAD

**Issue by Magdalena22** [antmicro-labs/open-source-video-previewer#7]
Is there any source/seller (TME?), from where we should use components?

**Comment by pgielda** [comment]
I would recommend anything that is possible to source from Mouser or digikey. TME is also ok. Just check if its in stock and not EOLed.

**Comment by pkatarzynski** [comment]
Please make sure the components will have Manufacturer and MPN (Manufacturer's Part Number) assigned. That allows to uniquely identify the component.  There are external BOM sourcing tools (like octopart's [bom tool](https://octopart.com/bom-tool)) that will find the distributors based on those data. You can then specify the preferred vendors depending on the location of the assembly house.
