### ISSUE TITLE
SD card slot

### ISSUE THREAD

**Issue by Magdalena22** [antmicro-labs/open-source-video-previewer#9]
Is removing SD card slot acceptable? It restricts usage to modules with integrated memory.

**Comment by pgielda** [comment]
Tough question ;)

The upside of having an external SD card (modules with "integrated memory" in fact have an onboard eMMC chip which you could define as an "SD-card-in-a-chip" ) is the fact that you can easily swap those (as well as use SD card to potentially re-flashing the built-in bootloader etc).
The downside is of course what you wrote above (+the fact that it takes PCB space)

But overall its your choice I guess.
